### ISSUE TITLE
MOTHA master checklist

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/models-of-the-hydrogen-atom#3]
#Sim Port Checklist Template

## Design
- [ ] **Design doc created** (Date: //) 
 - [ ] Make phethelp@gmail.com owner, share with phet-team
 - [ ] Add to [Master Doc List](https://docs.google.com/document/d/1yjT1oE95JG_evwob9LB_De-brD7JpfFM6iIL6pF812k/edit#)
- [ ] **Legacy sim docs/info gathered**
- [ ] **Learning goals and standards identified** (Date: //)
- [ ] **Design concept complete**  (Date: //)
- [ ] **Wireframes complete** (Date: //) 
- [ ] **Mockups complete** (Date: //) 
  - [ ] Mockups checked for colorblind and greyscale
- [ ] **Interviews complete** (Date: //) 
  - [ ] Results reported to team
  - [ ] Notes pasted into design doc
  - [ ] Back-up of interviews
- [ ] **Lead designer "sign off"** (Date: //) 
  - [ ] Performance acceptable
  - [ ] No new feature requests
- [ ] **Pre-publication items** 
  - [ ] Screenshot (2048x1344, PNG, 32-bit color, browser chrome stripped)
  - [ ] Check compatible activities  
  - [ ] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [ ] Teacher Guide
  - [ ] Activities and gooru spreadsheet
  - [ ] Notify translators?
  - [ ] Sim primer
  - [ ] Verify credits
- [ ] **Hold postmortem if applicable** (Date: //) 

## Implementation
- [ ] **Sim repo created** (Date: //) 
  - [ ] Collaborators added (such as QA team, designers, etc) 
  - [ ] Sim added to active repos list in chipper
  - [ ] Sim suggestions doc reviewed
  - [ ] Unfuddle tickets reviewed
  - [ ] Existing sim tested for bugs, issues reported in repo
  - [ ] Port existing strings (IF ANY) and commit to the GitHub repo
- [ ] **Initial development started** (Date: //)
- [ ] **Sim feature complete** (Date: //) 
- [ ] **Code review complete** (Date: //) 
  - [ ] Code review checklist
  - [ ] Model description 
- [ ] **Published** (Date: //)
  - [ ] Update repo README to published template

## QA
- [ ] **Dev testing complete** (Date: //) 
- [ ] **First release candidate** (Date: //) 
 - [ ] Test matrix deemed complete

**Comment by ariel-phet** [comment]
update and look into legacy testing

**Comment by pixelzoom** [comment]
Un-deferring, because developer has resumed for this sim.
