### ISSUE TITLE
Feature complete

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/models-of-the-hydrogen-atom#87]
As of [1.0.0-dev.14](https://phet-dev.colorado.edu/html/models-of-the-hydrogen-atom/1.0.0-dev.14), these are the features that need to be completed for the 1.0 release:

- [x] "3D Height" view for de Broglie
- [x] Electron Energy Level diagram
- [x] Spectrometer model & view - #48
- [x] Snapshots model & view - #48
- [x] Snapshots PhET-iO
- [x] Schrödinger state transition rules
- [x] Schrödinger view (performance problems, incorrect orbitals,...)
- [x] Schrödinger "Excite Atom" button - #55
- [x] Photons PhET-iO - #47
- [x] PhET-iO tree structure and metadata
- [x] PhET-iO State Wrapper
- [x] Misc. TODO comments
- [x] Oops dialog when Experiment is stuck in the metastable state.
- [x] Keyboard help dialog

**Comment by pixelzoom** [comment]
In Slack#DM, @kathy-phet asked for a status update. I replied:

> MOTHA is not feature complete. Status is at https://github.com/phetsims/models-of-the-hydrogen-atom/issues/87.  I’m currently working on Schrödinger state transition bugs that were present in the legacy version.  If I’m not pulled off on other things, I would anticipate 2/10 code review, 2/17 QA.

**Comment by pixelzoom** [comment]
We are feature complete. Closing.
